function dE_vs_RE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7,Y7)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6, X7, Y7)
%  X1:  scatter x
%  Y1:  scatter y
%  X2:  scatter x
%  Y2:  scatter y
%  X3:  scatter x
%  Y3:  scatter y
%  X4:  scatter x
%  Y4:  scatter y
%  X5:  scatter x
%  Y5:  scatter y
%  X6:  scatter x
%  Y6:  scatter y
%  X7:  scatter x
%  Y7:  scatter y

%  Auto-generated by MATLAB on 09-Dec-2018 23:15:33

% Create figure
figure1 = figure('Name','Confocal Profiles: d*E vs R*E',...
    'Position',[1 1 1920 1080]);

% Create axes
axes1 = axes('Position',...
    [0.0801479654747226 0.0901898734177215 0.898091401488678 0.834810126582279]);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'DisplayName','Gelest 12:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X2,Y2,'DisplayName','Gelest 9:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X3,Y3,'DisplayName','Gelest 8:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X4,Y4,'DisplayName','Gelest 7:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X5,Y5,'DisplayName','Dow Corning (OC)','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X6,Y6,'DisplayName','Dow Corning (RT)','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X7,Y7,'DisplayName','GEL-8100','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create xlabel
xlabel('R*E   (kg /s^2)','HorizontalAlignment','center','FontWeight','bold');

% Create ylabel
ylabel('\delta*E   (kg /s^2)','FontWeight','bold');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[1 10^4]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[1 10^3]);
box(axes1,'on');
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',16,'FontWeight','bold','XMinorTick','on','XScale',...
    'log','YMinorTick','on','YScale','log');

% Create line
annotation(figure1,'line',[0.19482120838471 0.716399506781751],...
    [0.26158940397351 0.897350993377483],'LineWidth',2,'LineStyle','--');

% Create line
annotation(figure1,'line',[0.197287299630086 0.870530209617756],...
    [0.263245033112583 0.529801324503311],'LineWidth',2,'LineStyle','--');


