function Vfl_vs_RE(X1, Y1, X2, Y2, X3, Y3,X4,Y4,X5,Y5)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  scatter x
%  Y1:  scatter y
%  X2:  scatter x
%  Y2:  scatter y
%  X3:  scatter x
%  Y3:  scatter y
%  X4:  scatter x
%  Y4:  scatter y

%  Auto-generated by MATLAB on 12-Apr-2018 19:16:43

% Create figure
figure1 = figure('Name','Confocal Profiles: V_fluid vs R*E');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'DisplayName','Gelest 9:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X2,Y2,'DisplayName','Gelest 8:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X3,Y3,'DisplayName','Gelest 12:1','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');
scatter(X4,Y4,'DisplayName','Dow Corning (Oven)','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');
scatter(X5,Y5,'DisplayName','Dow Corning (RT) ','MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create xlabel
xlabel('Sphere Radius, R*E','FontWeight','bold','FontSize',14);

% Create ylabel
ylabel('Displaced Fluid Volume, V_{fluid}','FontWeight','bold',...
    'FontSize',14);

axis([1e1 1e3 1e1 1e5])

% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on',...
    'YMinorTick','on','YScale','log');
% Create legend
legend(axes1,'show');
end