function Vfl_vs_Vunder(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4)
%  X1:  scatter x
%  Y1:  scatter y
%  X2:  scatter x
%  Y2:  scatter y
%  X3:  scatter x
%  Y3:  scatter y
%  X4:  scatter x
%  Y4:  scatter y

%  Auto-generated by MATLAB on 14-Jul-2018 16:37:02

% Create figure
figure1 = figure('Name','Confocal Profiles: V_fluid vs V_under');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,'DisplayName','Gelest 9:1 ( E ~ 5.12 kPa )',...
    'MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X2,Y2,'DisplayName','Gelest 12:1 ( E ~ 0.69 kPa )',...
    'MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X3,Y3,'DisplayName','Dow Corning (RT) ( E ~ 11.50 kPa )',...
    'MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create scatter
scatter(X4,Y4,'DisplayName','Dow Corning (OC) ( E ~ 11.08 kPa )',...
    'MarkerFaceColor','flat',...
    'MarkerEdgeColor','none');

% Create xlabel
%xlabel('Indented Volume, V_{under} (\mum^3)','FontWeight','bold',...
    %'FontSize',18);
xlabel('V_{indent} (\mum^3)','FontWeight','bold',...
    'FontSize',20);

% Create ylabel
%ylabel('Displaced Fluid Volume, V_{fluid} (\mum^3)','FontWeight','bold',...
    %'FontSize',18);
ylabel('V_{fluid} (\mum^3)','FontWeight','bold',...
    'FontSize',20);

axis([1e2 1e5 1e2 1e6]);
box(axes1,'on');


% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[100 100000]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[100 1000000]);
% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorTick','on','XScale','log','YGrid','on',...
    'YMinorTick','on','YScale','log');
set(axes1,'FontSize',16,'FontWeight','bold','XMinorTick','on','XScale',...
    'log','YMinorTick','on','YScale','log');
% Create line
annotation(figure1,'line',[0.19482120838471 0.716399506781751],...
    [0.26158940397351 0.897350993377483],'LineWidth',2,'LineStyle','--');

% Create line
annotation(figure1,'line',[0.197287299630086 0.870530209617756],...
    [0.263245033112583 0.529801324503311],'LineWidth',2,'LineStyle','--');

% Create legend
%legend1 = legend(axes1,'show');
%set(legend1,...'Position',[0.138947902835273 0.73870191800477 0.24147465437788 0.17710843373494],...'FontSize',14);

